FROM nginx:alpine

# Set up working directory
WORKDIR /usr/src/app

# Install Node.js and Angular CLI
RUN apk --no-cache add nodejs npm && npm install -g @angular/cli

# Copy frontend files and package.json
COPY frontend/ ./
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Build the Angular application
RUN ng build --configuration=production

# Remove the default NGINX configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy NGINX configuration
COPY frontend/nginx.conf /etc/nginx/conf.d/

# Copy the built application to NGINX's web directory
COPY /dist/buy-01 /usr/share/nginx/html

# Copy SSL certificates
COPY backend/microservices/api-gateway/src/main/resources/localhost.pem /etc/ssl/certs/
COPY backend/microservices/api-gateway/src/main/resources/localhost-key.pem /etc/ssl/private/

# Expose ports and start NGINX
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
