# Stage 1: Build the Angular application
FROM node:18-alpine as build

WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY frontend/package*.json ./

RUN npm install

# Copy the rest of the Angular project files into the container
COPY frontend/ ./

RUN npm run build --configuration=production

# Stage 2: Serve the built application with Nginx
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/dist/buy-01 /usr/share/nginx/html

# Copy the SSL certificates
COPY backend/microservices/api-gateway/src/main/resources/localhost.pem /etc/ssl/certs/
COPY backend/microservices/api-gateway/src/main/resources/localhost-key.pem /etc/ssl/private/

# Copy the Nginx configuration
COPY frontend/nginx.conf /etc/nginx/conf.d/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]




