version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile.jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backend_jenkins_home:/var/jenkins_home

volumes:
  backend_jenkins_home:
    external: true

