---
- name: Deploy to production
  gather_facts: false
  hosts: deployservers
  become: true
  become_user: root
  tasks:
  - name: Navigate to the repository directory and pull the latest changes
    shell: |
      cd ./to/buy-01/mr-jenk
      git pull origin main

  - name: Run create.sh
    shell: ./buy-01/mr-jenk/create.sh

  - name: Start Docker containers
    shell: cd ./buy-01/mr-jenk/backend && docker-compose up -d --build