FROM jenkins/jenkins:lts-jdk11

USER root

# Install Docker CLI (ARM compatible)
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

# Install Docker Compose (ARM compatible)
RUN curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-aarch64" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

USER jenkins
