spring:
  cloud:
    gateway:
      routes:
        - id: media-service
          uri: http://media-ms:8083
          predicates:
            - Path=/media/**
        - id: product-service
          uri: http://product-ms:8082
          predicates:
            - Path=/api/products/**
        - id: user-service
          uri: http://user-ms:8081
          predicates:
            - Path=/api/users/**
        - id: user-auth
          uri: http://user-ms:8081
          predicates:
            - Path=/api/auth/**